const Products = [
  {
    id: 1,
    image: "./ProductImg/Apple.png",
    name: "Apple",
    category: "freshfruit",
    description: "sale",
    discount: "Sale 50%",
    price: "$50.99",
    prices: 55.99,
    stars: 4.4,
    reviews: 50,
    tag: "healthy",
    Stock: true,
  },
  {
    id: 2,
    image: "./ProductImg/Mango.png",
    name: "Sarjapur Mango",
    category: "freshfruit",
    description: "popular",
    discount: "Sale 50%",
    price: "$100.99",
    prices: 100.99,
    stars: 5,
    reviews: 50,
    tag: "lowfat",
    Stock: true,
  },
  {
    id: 3,
    image: "./ProductImg/Tomato.png",
    name: "Red Tomato",
    category: "freshfruit",
    description: "latest",
    price: "$200",
    Prices: 200,
    stars: 4.4,
    reviews: 50,
    tag: "vegetarian",
    Stock: true,
  },
  {
    id: 4,
    image: "./ProductImg/Cowliflower.png",
    name: "Cowliflower",
    category: "vegetables",
    description: "latest",
    price: "$300",
    prices: 300.99,
    stars: 4.4,
    reviews: 50,
    Stock: true,
  },
  {
    id: 5,
    image: "./ProductImg/Chilli.png",
    name: "Green Chilli",
    category: "vegetables",
    description: "sale",
    discount: "Sale 50%",
    price: "$400.99",
    prices: 400,
    stars: 3,
    reviews: 50,
  },
  {
    id: 6,
    image: "./ProductImg/Eggplant.png",
    name: "Eggplant",
    category: "vegetables",
    description: "latest",
    price: "$500.99",
    prices: 500,
    stars: 2.5,
    reviews: 50,
    Stock:true,
  },
  {
    id: 7,
    image: "./ProductImg/Lettuce.png",
    name: "Lettuce",
    category: "cooking",
    description: "sale",
    discount: "Sale 50%",
    price: "$600.99",
    prices: 600,
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 8,
    image: "./ProductImg/Big.png",
    name: "Big",
    category: "cooking",
    description: "popular",
    price: "$700.99",
    prices: 700,
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 18,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "popular",
    price: "$800.99",
    prices: 800,
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 9,
    image: "./ProductImg/Apple.png",
    name: "Apple",
    category: "fruit",
    description: "sale",
    discount: "Sale 50%",
    price: "$900.99",
    prices: 900,
    stars: 4,
    reviews: 50,
  },
  {
    id: 10,
    image: "./ProductImg/Mango.png",
    name: "Sarjapur Mango",
    category: "fruit",
    description: "popular",
    discount: "Sale 50%",
    price: "$1000.99",
    prices: 1000,
    stars: 5,
    reviews: 50,
  },
  {
    id: 11,
    image: "./ProductImg/Tomato.png",
    name: "Red Tomato",
    category: "vegetable",
    description: "loremjncjnd",
    price: "$1100.99",
    prices: 1100,
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 12,
    image: "./ProductImg/Cowliflower.png",
    name: "Cowliflower",
    category: "vegetable",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 13,
    image: "./ProductImg/Chilli.png",
    name: "Green Chilli",
    category: "vegetable",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 14,
    image: "./ProductImg/Eggplant.png",
    name: "Eggplant",
    category: "vegetable",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 2.5,
    reviews: 50,
  },
  {
    id: 15,
    image: "./ProductImg/Lettuce.png",
    name: "Lettuce",
    category: "vegetable",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 16,
    image: "./ProductImg/Big.png",
    name: "Big",
    category: "Vegetable",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 17,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 18,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 19,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 20,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 21,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 22,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 23,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 24,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 25,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 26,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 27,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 28,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 29,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 30,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
];

export default Products;
