const ProductMenu = [
  {
    id: 1,
    image: "./ProductImg/Apple.png",
    name: "Apple",
    category: "fruit",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 2,
    image: "./ProductImg/Mango.png",
    name: "Sarjapur Mango",
    category: "fruit",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: "$14.99",
    stars: 5,
    reviews: 50,
  },
  {
    id: 3,
    image: "./ProductImg/Tomato.png",
    name: "Red Tomato",
    category: "vegetable",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 4,
    image: "./ProductImg/Cowliflower.png",
    name: "Cowliflower",
    category: "vegetable",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 5,
    image: "./ProductImg/Chilli.png",
    name: "Green Chilli",
    category: "vegetable",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 6,
    image: "./ProductImg/Eggplant.png",
    name: "Eggplant",
    category: "vegetable",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 2.5,
    reviews: 50,
  },
  {
    id: 7,
    image: "./ProductImg/Lettuce.png",
    name: "Lettuce",
    category: "vegetable",
    description: "loremjncjnd",
    discount: "Sale 50%",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 8,
    image: "./ProductImg/Big.png",
    name: "Big",
    category: "Vegetable",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
  {
    id: 8,
    image: "./ProductImg/Apple.png",
    name: "Chicken Apple",
    category: "meatandfish",
    description: "loremjncjnd",
    price: "$14.99",
    stars: 4.4,
    reviews: 50,
  },
];
export default ProductMenu;
